layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.6011856
  lightness: 0.4641577
  rhythmicContrast: 0.6666667
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.3207885
name: A State Of Wanderlust
